#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MobileApp.Droid.Resource", IsApplication=true)]

namespace MobileApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int fragment_close_enter = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int fragment_close_exit = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int fragment_fade_enter = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int fragment_fade_exit = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int fragment_fast_out_extra_slow_in = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int fragment_open_enter = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int fragment_open_exit = 2130771974;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int alpha = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int coordinatorLayoutStyle = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int drawerLayoutStyle = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int elevation = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int font = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int fontProviderAuthority = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int fontProviderCerts = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int fontProviderFetchStrategy = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int fontProviderFetchTimeout = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int fontProviderPackage = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int fontProviderQuery = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int fontStyle = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int fontVariationSettings = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int fontWeight = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int keylines = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int layout_anchor = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int layout_anchorGravity = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int layout_behavior = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int layout_dodgeInsetEdges = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int layout_insetEdge = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int layout_keyline = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int statusBarBackground = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int swipeRefreshLayoutProgressSpinnerBackgroundColor = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int ttcIndex = 2130837527;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int androidx_core_ripple_material_light = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int androidx_core_secondary_text_default_material_light = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int browser_actions_bg_grey = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int browser_actions_divider_color = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int browser_actions_text_color = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int browser_actions_title_color = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int colorAccent = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int colorPrimary = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int colorPrimaryDark = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int launcher_background = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int notification_action_color_filter = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int notification_icon_bg_color = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int notification_material_background_media_default_color = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int primary_text_default_material_dark = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int secondary_text_default_material_dark = 2130903054;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public const int browser_actions_context_menu_max_width = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int browser_actions_context_menu_min_padding = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int compat_button_inset_horizontal_material = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int compat_button_inset_vertical_material = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int compat_button_padding_horizontal_material = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int compat_button_padding_vertical_material = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int compat_control_corner_material = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int compat_notification_large_icon_max_height = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int compat_notification_large_icon_max_width = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int def_drawer_elevation = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int notification_action_icon_size = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int notification_action_text_size = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int notification_big_circle_margin = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int notification_content_margin_start = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int notification_large_icon_height = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int notification_large_icon_width = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int notification_main_column_padding_top = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int notification_media_narrow_margin = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int notification_right_icon_size = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int notification_right_side_padding_top = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int notification_small_icon_background_padding = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int notification_small_icon_size_as_large = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int notification_subtext_size = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int notification_top_pad = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int notification_top_pad_large_text = 2130968600;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public const int icon_about = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_feed = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int notification_action_background = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int notification_bg = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int notification_bg_low = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int notification_bg_low_normal = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int notification_bg_low_pressed = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int notification_bg_normal = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int notification_bg_normal_pressed = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int notification_icon_background = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int notification_template_icon_bg = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int notification_template_icon_low_bg = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int notification_tile_bg = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int notify_panel_notification_icon_bg = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int xamarin_logo = 2131034126;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060000
			public const int accessibility_action_clickable_span = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int accessibility_custom_action_0 = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int accessibility_custom_action_1 = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int accessibility_custom_action_10 = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int accessibility_custom_action_11 = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int accessibility_custom_action_12 = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int accessibility_custom_action_13 = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int accessibility_custom_action_14 = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int accessibility_custom_action_15 = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int accessibility_custom_action_16 = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int accessibility_custom_action_17 = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int accessibility_custom_action_18 = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int accessibility_custom_action_19 = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int accessibility_custom_action_2 = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int accessibility_custom_action_20 = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int accessibility_custom_action_21 = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int accessibility_custom_action_22 = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int accessibility_custom_action_23 = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int accessibility_custom_action_24 = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int accessibility_custom_action_25 = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int accessibility_custom_action_26 = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int accessibility_custom_action_27 = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int accessibility_custom_action_28 = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int accessibility_custom_action_29 = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int accessibility_custom_action_3 = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int accessibility_custom_action_30 = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int accessibility_custom_action_31 = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int accessibility_custom_action_4 = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int accessibility_custom_action_5 = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int accessibility_custom_action_6 = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int accessibility_custom_action_7 = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int accessibility_custom_action_8 = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int accessibility_custom_action_9 = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int action0 = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int actions = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int ActionSearch = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int action_container = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int action_divider = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int action_image = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int action_text = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int all = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int async = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int blocking = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int bottom = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public const int browser_actions_header_text = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int browser_actions_menu_items = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public const int browser_actions_menu_item_icon = 2131099694;
			
			// aapt resource value: 0x7F06002F
			public const int browser_actions_menu_item_text = 2131099695;
			
			// aapt resource value: 0x7F060030
			public const int browser_actions_menu_view = 2131099696;
			
			// aapt resource value: 0x7F060031
			public const int cancel_action = 2131099697;
			
			// aapt resource value: 0x7F060032
			public const int center = 2131099698;
			
			// aapt resource value: 0x7F060033
			public const int center_horizontal = 2131099699;
			
			// aapt resource value: 0x7F060034
			public const int center_vertical = 2131099700;
			
			// aapt resource value: 0x7F060035
			public const int chronometer = 2131099701;
			
			// aapt resource value: 0x7F060036
			public const int clip_horizontal = 2131099702;
			
			// aapt resource value: 0x7F060037
			public const int clip_vertical = 2131099703;
			
			// aapt resource value: 0x7F060038
			public const int dialog_button = 2131099704;
			
			// aapt resource value: 0x7F060039
			public const int end = 2131099705;
			
			// aapt resource value: 0x7F06003A
			public const int end_padder = 2131099706;
			
			// aapt resource value: 0x7F06003B
			public const int fill = 2131099707;
			
			// aapt resource value: 0x7F06003C
			public const int fill_horizontal = 2131099708;
			
			// aapt resource value: 0x7F06003D
			public const int fill_vertical = 2131099709;
			
			// aapt resource value: 0x7F06003E
			public const int forever = 2131099710;
			
			// aapt resource value: 0x7F06003F
			public const int fragment_container_view_tag = 2131099711;
			
			// aapt resource value: 0x7F060040
			public const int icon = 2131099712;
			
			// aapt resource value: 0x7F060041
			public const int icon_group = 2131099713;
			
			// aapt resource value: 0x7F060042
			public const int info = 2131099714;
			
			// aapt resource value: 0x7F060043
			public const int italic = 2131099715;
			
			// aapt resource value: 0x7F060044
			public const int left = 2131099716;
			
			// aapt resource value: 0x7F060045
			public const int line1 = 2131099717;
			
			// aapt resource value: 0x7F060046
			public const int line3 = 2131099718;
			
			// aapt resource value: 0x7F060047
			public const int media_actions = 2131099719;
			
			// aapt resource value: 0x7F060048
			public const int media_controller_compat_view_tag = 2131099720;
			
			// aapt resource value: 0x7F060049
			public const int none = 2131099721;
			
			// aapt resource value: 0x7F06004A
			public const int normal = 2131099722;
			
			// aapt resource value: 0x7F06004B
			public const int notification_background = 2131099723;
			
			// aapt resource value: 0x7F06004C
			public const int notification_main_column = 2131099724;
			
			// aapt resource value: 0x7F06004D
			public const int notification_main_column_container = 2131099725;
			
			// aapt resource value: 0x7F06004E
			public const int right = 2131099726;
			
			// aapt resource value: 0x7F06004F
			public const int right_icon = 2131099727;
			
			// aapt resource value: 0x7F060050
			public const int right_side = 2131099728;
			
			// aapt resource value: 0x7F060051
			public const int sliding_tabs = 2131099729;
			
			// aapt resource value: 0x7F060052
			public const int start = 2131099730;
			
			// aapt resource value: 0x7F060053
			public const int status_bar_latest_event_content = 2131099731;
			
			// aapt resource value: 0x7F060054
			public const int tag_accessibility_actions = 2131099732;
			
			// aapt resource value: 0x7F060055
			public const int tag_accessibility_clickable_spans = 2131099733;
			
			// aapt resource value: 0x7F060056
			public const int tag_accessibility_heading = 2131099734;
			
			// aapt resource value: 0x7F060057
			public const int tag_accessibility_pane_title = 2131099735;
			
			// aapt resource value: 0x7F060058
			public const int tag_screen_reader_focusable = 2131099736;
			
			// aapt resource value: 0x7F060059
			public const int tag_transition_group = 2131099737;
			
			// aapt resource value: 0x7F06005A
			public const int tag_unhandled_key_event_manager = 2131099738;
			
			// aapt resource value: 0x7F06005B
			public const int tag_unhandled_key_listeners = 2131099739;
			
			// aapt resource value: 0x7F06005C
			public const int text = 2131099740;
			
			// aapt resource value: 0x7F06005D
			public const int text2 = 2131099741;
			
			// aapt resource value: 0x7F06005E
			public const int time = 2131099742;
			
			// aapt resource value: 0x7F06005F
			public const int title = 2131099743;
			
			// aapt resource value: 0x7F060060
			public const int toolbar = 2131099744;
			
			// aapt resource value: 0x7F060061
			public const int top = 2131099745;
			
			// aapt resource value: 0x7F060062
			public const int view_tree_saved_state_registry_owner = 2131099746;
			
			// aapt resource value: 0x7F060063
			public const int visible_removing_fragment_view_tag = 2131099747;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public const int cancel_button_image_alpha = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int status_bar_notification_info_maxnum = 2131165185;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public const int browser_actions_context_menu_page = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int browser_actions_context_menu_row = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int custom_dialog = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int notification_action = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int notification_action_tombstone = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int notification_media_action = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int notification_media_cancel_action = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int notification_template_big_media = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int notification_template_big_media_custom = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int notification_template_big_media_narrow = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int notification_template_big_media_narrow_custom = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int notification_template_custom_big = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int notification_template_icon_group = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int notification_template_lines_media = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int notification_template_media = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int notification_template_media_custom = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int notification_template_part_chronometer = 2131230736;
			
			// aapt resource value: 0x7F080011
			public const int notification_template_part_time = 2131230737;
			
			// aapt resource value: 0x7F080012
			public const int Tabbar = 2131230738;
			
			// aapt resource value: 0x7F080013
			public const int Toolbar = 2131230739;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F090000
			public const int MainMenu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F0A0000
			public const int icon = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int icon_round = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int launcher_foreground = 2131361794;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0B0000
			public const int copy_toast_msg = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int fallback_menu_item_copy_link = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int fallback_menu_item_open_in_browser = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int fallback_menu_item_share_link = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public const int status_bar_notification_info_overflow = 2131427332;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0C0000
			public const int MainTheme = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int TextAppearance_Compat_Notification = 2131492865;
			
			// aapt resource value: 0x7F0C0002
			public const int TextAppearance_Compat_Notification_Info = 2131492866;
			
			// aapt resource value: 0x7F0C0003
			public const int TextAppearance_Compat_Notification_Info_Media = 2131492867;
			
			// aapt resource value: 0x7F0C0004
			public const int TextAppearance_Compat_Notification_Line2 = 2131492868;
			
			// aapt resource value: 0x7F0C0005
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131492869;
			
			// aapt resource value: 0x7F0C0006
			public const int TextAppearance_Compat_Notification_Media = 2131492870;
			
			// aapt resource value: 0x7F0C0007
			public const int TextAppearance_Compat_Notification_Time = 2131492871;
			
			// aapt resource value: 0x7F0C0008
			public const int TextAppearance_Compat_Notification_Time_Media = 2131492872;
			
			// aapt resource value: 0x7F0C0009
			public const int TextAppearance_Compat_Notification_Title = 2131492873;
			
			// aapt resource value: 0x7F0C000A
			public const int TextAppearance_Compat_Notification_Title_Media = 2131492874;
			
			// aapt resource value: 0x7F0C000B
			public const int Widget_Compat_NotificationActionContainer = 2131492875;
			
			// aapt resource value: 0x7F0C000C
			public const int Widget_Compat_NotificationActionText = 2131492876;
			
			// aapt resource value: 0x7F0C000D
			public const int Widget_Support_CoordinatorLayout = 2131492877;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F020000,0x101031F,0x10101A5 }
			public static int[] ColorStateListItem = new int[] {
					2130837504,
					16843551,
					16843173};
			
			// aapt resource value: 0
			public const int ColorStateListItem_alpha = 0;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 2
			public const int ColorStateListItem_android_color = 2;
			
			// aapt resource value: { 0x7F02000E,0x7F020015 }
			public static int[] CoordinatorLayout = new int[] {
					2130837518,
					2130837525};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: { 0x10100B3,0x7F02000F,0x7F020010,0x7F020011,0x7F020012,0x7F020013,0x7F020014 }
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130837519,
					2130837520,
					2130837521,
					2130837522,
					2130837523,
					2130837524};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_anchor = 1;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 2;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_behavior = 3;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_keyline = 6;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			// aapt resource value: { 0x7F020003 }
			public static int[] DrawerLayout = new int[] {
					2130837507};
			
			// aapt resource value: 0
			public const int DrawerLayout_elevation = 0;
			
			// aapt resource value: { 0x7F020005,0x7F020006,0x7F020007,0x7F020008,0x7F020009,0x7F02000A }
			public static int[] FontFamily = new int[] {
					2130837509,
					2130837510,
					2130837511,
					2130837512,
					2130837513,
					2130837514};
			
			// aapt resource value: { 0x1010532,0x101053F,0x1010570,0x1010533,0x101056F,0x7F020004,0x7F02000B,0x7F02000C,0x7F02000D,0x7F020017 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844095,
					16844144,
					16844083,
					16844143,
					2130837508,
					2130837515,
					2130837516,
					2130837517,
					2130837527};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontStyle = 1;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontVariationSettings = 2;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_fontWeight = 3;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_ttcIndex = 4;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x10100D0,0x1010003,0x10100D1 }
			public static int[] Fragment = new int[] {
					16842960,
					16842755,
					16842961};
			
			// aapt resource value: { 0x1010003,0x10100D1 }
			public static int[] FragmentContainerView = new int[] {
					16842755,
					16842961};
			
			// aapt resource value: 0
			public const int FragmentContainerView_android_name = 0;
			
			// aapt resource value: 1
			public const int FragmentContainerView_android_tag = 1;
			
			// aapt resource value: 0
			public const int Fragment_android_id = 0;
			
			// aapt resource value: 1
			public const int Fragment_android_name = 1;
			
			// aapt resource value: 2
			public const int Fragment_android_tag = 2;
			
			// aapt resource value: { 0x101020B,0x10101A2,0x10101A3,0x101019E,0x1010512,0x1010513,0x10101A4,0x101019D,0x1010510,0x1010511,0x1010201,0x10101A1 }
			public static int[] GradientColor = new int[] {
					16843275,
					16843170,
					16843171,
					16843166,
					16844050,
					16844051,
					16843172,
					16843165,
					16844048,
					16844049,
					16843265,
					16843169};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 0
			public const int GradientColor_android_centerColor = 0;
			
			// aapt resource value: 1
			public const int GradientColor_android_centerX = 1;
			
			// aapt resource value: 2
			public const int GradientColor_android_centerY = 2;
			
			// aapt resource value: 3
			public const int GradientColor_android_endColor = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_endX = 4;
			
			// aapt resource value: 5
			public const int GradientColor_android_endY = 5;
			
			// aapt resource value: 6
			public const int GradientColor_android_gradientRadius = 6;
			
			// aapt resource value: 7
			public const int GradientColor_android_startColor = 7;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 10
			public const int GradientColor_android_tileMode = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_type = 11;
			
			// aapt resource value: { 0x7F020016 }
			public static int[] SwipeRefreshLayout = new int[] {
					2130837526};
			
			// aapt resource value: 0
			public const int SwipeRefreshLayout_swipeRefreshLayoutProgressSpinnerBackgroundColor = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0E0000
			public const int image_share_filepaths = 2131623936;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
